const generate = document.getElementById('generate');
const pEl = document.getElementById('pEl');
const prompts = [
    'Write about a person who always makes you laugh.', 
    'What was the best gift you received as a child?', 
    'Write about an event in your life that changed it for the better.', 
    'Who has loved you unconditionally?',
    'What guilty pleasure are you secretly grateful for?', 
    'Write about a person you are grateful for, but sometimes take for granted.',
    'What about today made you smile?', 
    'What did you eat this week that was delicious?', 
    'What is something great about your community?',
    'Write about something that always makes you smile, no matter what.', 
    'What about your living space are you especially thankful for?',
    'Write down one good thing that happened to you today.',
    'What in your childhood are you grateful for?',
    'Who served as a mentor to you (whether they knew it or not)?', 
    'Write about three skills or talents you have that serve you well.',
    'What do you really appreciate about your life?', 
    'What has surprised you, in a good way?', 
    'Describe your favorite mundane moment of the day.',
    'What gift have you given that has made a difference in someone’s life?', 
    'Write about a positive interaction you had with a stranger.', 
    'Who or what in your life are you happy to have let go?',
    'List 5 positive qualities of the first person you usually talk to each day.',
    'What was your best day ever?', 
    'List 5 things that spark your curiosity and inspire your interest.',
    'What friend are you most grateful for? What makes them special?', 
    'What makes you laugh so hard you get tears in your eyes?', 
    'Where is your “happy place”? Describe it.',
    'What positive impact did you have this week?', 
    'What could you do this week to express gratitude to others?', 
    'What one thing do you own that makes every day a little bit easier?',
    'What character trait are you most grateful for?', 
    'What adversity are you grateful for?', 
    'What are your favorite things in the natural world?', 
    'What about your daily routine are you grateful for?',
    'What do you deeply enjoy doing alone?', 
    'Did a stranger ever do a favor for you?',
    'Write about something you think is adorable.', 
    'What 5 songs are you grateful for? Why?', 
    'Write about what makes your pet so special.',
    'What freedoms are you grateful for?', 
    'How have you grown in the past year?',
    'What book or movie are you grateful for? How did it impact you?', 
    'Write about a favorite memory.',
    'Which day was more special than any other?',
    'What’s the most memorable conversation you’ve had in the past year?',
    'Who helps you achieve your goals?', 
    'List 10 frivolous things that bring you joy.',
    'What could you not live without?',
    'Write about a random act of kindness.',
    'Who taught you about unconditional love?', 
    'What about your upbringing are you most grateful for?',
    'Who made you feel good this week?',      
    'Describe yourself in 10 words or less.', 
    'What’s your passion, and how did you discover it?', 
    'What in your life has given you the greatest fulfillment?', 
    'If you knew you wouldn’t fail, what would you do?',
    'What’s your biggest dream? Is there a smaller version of your dream that you could accomplish in two weeks?',
    'What have you learned that has changed your values?',
    'Write about a “hell no” moment—a time when you were so outraged, you couldn’t help but take action.', 
    'Fast forward to your 90th birthday. What would you want your favorite future relative (who doesn’t exist yet) to say about your life?',
    'Where do you show leadership?', 
    'What are your plans for going after what your heart wants?', 
    'What do you wish you were doing more of?', 
    'Who do you want to spend more time with? Why?', 
    'Who do you want to be in three years? How do you want people to see you?', 
    'What’s the most important thing to focus on this week?',
    'Where are you giving something that you don’t actually want to give?', 
    'When people complain about you, what do they say?', 
    'What expectation do others have of you that you wish they didn’t?',
    'What demand(s) on your time do you need to get out of? ',
    'What is the one thing you need to focus on now, that will make everything else better in the future?', 
    'What one discipline sparks your personal growth the most?', 
    'What three keystone habits do you need to perform daily?', 
    'If you had $150,000 to spend in 24 hours or less, how would you spend it?', 
    'What do you happily spend a lot of money on (without feeling guilty about it), but suspect others might judge you for?',
    'What do you need to stop doing?', 
    'If you only had two years to live, what would you most want to accomplish?', 
    'Create a schedule for your dream life.',
    'What are you most excited about right now?',
    'What is your favorite way to start the day?', 
    'What do you need to say to someone that you are afraid to say?', 
    'What would you like to be remembered for?',
    'List 3 of the best compliments you’ve received.',
    'Write about a mistake that turned out to be a blessing.', 
    'What’s the most ridiculous thing you’ve ever purchased? Did it turn out okay?',
    'What rule do you most want to break? (Or what rule have you broken that you wish you hadn’t?)',
    'Where does your future self live? What does that look like?', 
    'If you could go back 10 years and spend 5 minutes with your former self, what advice would you share?', 
    'When you are working in an optimal job, what do you enjoy the most?', 
    'If you could spend twelve hours doing anything you want, anywhere you want, how would you spend them?',
    'How do you feel about current events? What worries you, and what gives you hope?',
    'Are you an Eeyore or a Tigger?',
    'What kinds of activities take up most of your time? Are you happy about that? If not, what could you give up to gain back 30 minutes?', 
    'What’s important to you right now?', 
    'List 10 of your favorite things.',
    'What task are you putting off that you just need to get done? How could you finish it within the next week?', 
    'Has there ever been a time you were on a path and something happened to completely shift your trajectory?',
    'What are you thinking of doing that you are afraid to tell anyone about?', 
    'What are you holding onto too tightly?', 
    'How could you play more?', 
    'What question are you grappling with?',
    'What makes you feel overwhelmed or paralyzed? Who could you ask for help?',
    'What is something you have always wanted to try, but never have?',
    'What time of day are you most creative? How do you want to use that time?',
    'What is your time frame for achieving your dream?',
    'What do you value most?',
    'What are you not saying that needs to be said?',
    'What decision(s) are you procrastinating on making?',
    'What’s your biggest priority this month?',
    'What gets you excited about the future?',
    'What are your core values?',
    'What is your take on love?',
    'Why do you live where you do?',
    'What is your favorite thing about your current living space? What drives you crazy?',
    'Write down the steps you need to take to get from who you are to who you want to be.', 
    'How are you contributing to the situation in your life that frustrates you the most?',
    'What is your personal definition of success, stripped of others’ expectations?',
    'What would you write, if you felt it wouldn’t be judged?', 
    'What short-term losses are you willing to accept now, for longer-term gains in the future?',
    'If people become the amalgamation of the 5 people they spend the most time with, who are you going to be?',
    'When everything else is stripped away, and no one else’s opinion is influencing you, what is your truth?', 
    'Write your future self a letter that begins: “Dear future me, this is what I want for you…”',
    'When did you last boldly take action?',
    'What is your relationship with technology?',  
    'What skill do you need to learn to advance to the next level?',
    'What place do you want to visit, but haven’t been to yet?', 
    'What’s the hardest thing you’ve ever done?',
    'Who in my life can I be my full self with, unapologetically?', 
    'What am I doing when I feel most free?', 
    'Who am I, outside of the roles I play?', 
    'What do I need to forgive myself for?', 
    'Am I a victim or a hero in my own story?',
    'What do I need to do to change for the better?  ',
    'What am I feeling right now? How long have I had this feeling? ',
    'Who triggers negative emotions in me? Why? ',
    'Who triggers positive emotions in me? Why?',
    'When I get caught in a thinking loop, what am I thinking about?',
    'When have I cried happy tears? What made that happen?',
    'Who have I lied to? Why? What would have happened if I’d told the truth?',
    'What is my biggest regret? How can I make amends?',
    'What is something I am angry about, but haven’t dealt with?   ',
    'How do I feel about the statement: “I am enough”?',
    'What do I not get credit for?',
    'Would I parent your children in the same way I was parented? Why or why not? ',
    'My past doesn’t define who I am because… ',
    'I have trouble sleeping when…',
    'How would I tell the story of my life in three sentences? ',
    '“Dear [name of a person I’ve lost], …”',
    'One area I need to improve on is… ',
    'Right now, my thoughts are _____________. I wish they were _______________.',
    'I really wish others knew this about me: …',
    'What barrier(s) do I need to overcome?',
    'Who made you feel good this week?',
    'What was the biggest mistake you made this week?',
    'What did you do this week that moved you closer to reaching your goals?',
    'Is there anything you did this week that you wish you’d done differently?',
    'What did you most enjoy doing this week?',
    'How did you procrastinate on important tasks this week?',
    'What did you learn this week?',
    'What’s the funniest thing that happened to you this week?',
];

console.log(pEl);

function randomPrompt() {
let prompt = prompts[Math.floor(Math.random() * prompts.length)];
let promptToString = prompt.toString();
return promptToString; 
}

generate.addEventListener("click", function() {
console.log('clicked generate')
let prompt = prompts[Math.floor(Math.random() * prompts.length)];
let promptToString = prompt.toString();
pEl.innerHTML = promptToString; 
})
